document.write("<nav class='h_navbar'>")
document.write("<ul>")
document.write("<li><a href=''>Name(ID)</a></li>")
document.write("<li ><a href='signin_v1.html'>Logout</a></li>")
document.write("</ul>")
document.write("</nav>")
document.write("<nav class='v_navbar'>")
document.write("<ul>")
document.write("<li><img src='Photoes/home.png'><a href='Student-home.html'>Home</a></li>")
document.write("<li><img src='Photoes/info.png'><a href=''>Information</a></li> ")
document.write("<li><img src='Photoes/timetable.png'><a href=''>TimeTable</a></li> ")
document.write("</ul>")
document.write("</nav>")
